### ISSUE TITLE
"resume" is inconsistent

### ISSUE THREAD

**Issue by stephen-zhao** [asmod3ous/asmod3ous.gihub.io#1]
https://github.com/asmod3ous/asmod3ous.gihub.io/blob/7247a56fc51272b5e28843cea88ee47c89b172ff/scripts.js#L420

Seems there is inconsistency around this area.

In the radar graph, `d5[4]` is labeled as "resume".

In the text, `d5[4]` is labeled as "quantity".

Also in the text, a weighted sum of the top 4 (out of Dmg, Speed, Bruiser, Support, Quantity) is labeled as "resume".

So what is "resume"? Is it supposed to be a summary number? Should that really be `d5[4]` in the graph? or should it use the `overall` too? Is the graph perhaps mislabeled, and should say "quantity" for d5[4] too?

**Comment by stephen-zhao** [comment]
Oh, sorry might have submitted this onto the wrong repo. Noticed there's a separate one where more up-to-date dev work is at. Though my question seems to apply to that one too? Not entirely sure as haven't had chance to look at that one.

**Comment by asmod3ous** [comment]
Hi! I will check that, thanks for the notice.

**Comment by asmod3ous** [comment]
It has crossed data, just added a provisory fix before next refactor.
